export const ADDPRODUCT = "ADDPRODUCT" ;
export const ADDPRODUCT_SUCCESS = "ADDPRODUCT_SUCCESS" ;
export const ADDPRODUCT_FAIL = "ADDPRODUCT_FAIL" ;
export const GETPRODUCTS = "GETPRODUCTS";
export const UPDATEPRODUCT = "UPDATEPRODUCT";
export const DELETEPRODUCT = "DELETEPRODUCT";
export const DETAILPRODUCT = "DETAILPRODUCT";
export const GET_DIGITAL_PRODUCT = "GET_DIGITAL_PRODUCT";